# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_auto_20160227_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
